### ISSUE TITLE
Add new prusa camera api connection

### ISSUE THREAD

**Issue by yasars** [johnyHV/PrusaConnect_ESP32-CAM#1]
Hi prusa add an new option to prusa connect.... you must use your api...
https://connect.prusa3d.com/docs/cameras/

When you add this feature we can more easy add cameras to prusa ...

Go to add you see an token add this to your xam and voilla.... i hope you can do it
![Screenshot_20230830-110448](https://github.com/johnyHV/PrusaConnect_ESP32-CAM/assets/41986136/f9761df7-e3c4-4d66-a2f1-2bdcb852f592)

**Comment by keyboard-magpie** [comment]
w.r.t. this and current code- prusaconnect no longer appears to issue the fingerprint. I'm trying just now to see if registering a camera just with the token given is enough.

**Comment by johnyHV** [comment]
I working on the fix this issue and update docu

**Comment by yasars** [comment]
Yout latest version has an bug....



Miroslav Pivovarsky ***@***.***> schrieb am Sa., 16. Sept.
2023, 16:23:

**Comment by johnyHV** [comment]
what bug?

**Comment by yasars** [comment]
I send you an picture... From the Screenshot from the cam

**Comment by johnyHV** [comment]
where you are send me screen shot ? you mean feature with camera flashing ? it's not bug. its feature...

**Comment by yasars** [comment]
No my friend... I send you an email with the little bug and screeshot... Look into your email account

**Comment by johnyHV** [comment]
I have no email from you
